export const cursoOptions = [
    { "value": "MEDICINA_VETERINARIA", "label": "Medicina Veterinária" },
    { "value": "ENGENHARIA_AGRONOMICA", "label": "Engenharia Agronômica" },
    { "value": "ENGENHARIA_MECANICA", "label": "Engenharia Mecânica" },
    { "value": "BANCO_DE_DADOS", "label": "Banco de Dados" },
    { "value": "SEGURANCA_NO_TRABALHO", "label": "Segurança no Trabalho" },
    { "value": "LICENCIATURA_HISTORIA", "label": "Licenciatura em História" },
    { "value": "ENGENHARIA_PRODUCAO", "label": "Engenharia de Produção" },
    { "value": "FISIOTERAPIA", "label": "Fisioterapia" },
    { "value": "DESIGN_MODA", "label": "Design de Moda" },
    { "value": "GESTAO_QUALIDADE", "label": "Gestão da Qualidade" },
    { "value": "BIOMEDICINA", "label": "Biomedicina" },
    { "value": "SISTEMAS_INFORMACAO", "label": "Sistemas de Informação" },
    { "value": "CIENCIAS_COMPUTACAO", "label": "Ciências da Computação" },
    { "value": "CIENCIAS_ECONOMICAS", "label": "Ciências Econômicas" },
    { "value": "GESTAO_RECURSOS_HUMANOS", "label": "Gestão de Recursos Humanos" },
    { "value": "PSICOLOGIA", "label": "Psicologia" },
    { "value": "PROCESSOS_ESCOLARES", "label": "Processos Escolares" },
    { "value": "ADS", "label": "Análise e Desenvolvimento de Sistemas" },
    { "value": "DESIGN_INTERIORES", "label": "Design de Interiores" },
    { "value": "ENGENHARIA_SOFTWARE", "label": "Engenharia de Software" },
    { "value": "MEDICINA", "label": "Medicina" },
    { "value": "RADIOLOGIA", "label": "Radiologia" },
    { "value": "NUTRICAO", "label": "Nutrição" },
    { "value": "ODONTOLOGIA", "label": "Odontologia" },
    { "value": "LETRAS_PORTUGUES", "label": "Bacharelado em Letras - Língua Portuguesa" },
    { "value": "FARMACIA", "label": "Farmácia" },
    { "value": "GESTAO_COMERCIAL", "label": "Gestão Comercial" },
    { "value": "PUBLICIDADE_PROPAGANDA", "label": "Publicidade e Propaganda" },
    { "value": "ENGENHARIA_QUIMICA", "label": "Engenharia Química" },
    { "value": "CIENCIA_DADOS", "label": "Ciência de Dados" },
    { "value": "DEFESA_CIBERNETICA", "label": "Defesa Cibernética" },
    { "value": "JOGOS_DIGITAIS", "label": "Jogos Digitais" },
    { "value": "ARQUITETURA_URBANISMO", "label": "Arquitetura e Urbanismo" },
    { "value": "ADMINISTRACAO_PUBLICA", "label": "Administração Pública" },
    { "value": "JORNALISMO", "label": "Jornalismo" },
    { "value": "DESIGN_GRAFICO", "label": "Design Gráfico" },
    { "value": "CIENCIAS_BIOLOGICAS", "label": "Ciências Biológicas - Bacharelado" },
    { "value": "GESTAO_PUBLICA", "label": "Gestão Pública" },
    { "value": "GESTAO_AMBIENTAL", "label": "Gestão Ambiental" },
    { "value": "INVESTIGACAO_FORENSE", "label": "Investigação Forense e Perícia Criminal" },
    { "value": "LETRAS_INGLES", "label": "Licenciatura em Língua Inglesa" },
    { "value": "LOGISTICA", "label": "Logística" },
    { "value": "GESTAO_SEGURANCA_PRIVADA", "label": "Gestão de Segurança Privada" },
    { "value": "ESTETICA_COSMETICA", "label": "Estética e Cosmética" },
    { "value": "ADMINISTRACAO", "label": "Administração" },
    { "value": "COMUNICACAO_INSTITUCIONAL", "label": "Comunicação Institucional" },
    { "value": "SERVICOS_JURIDICOS", "label": "Serviços Jurídicos e Notariais" },
    { "value": "DESIGN", "label": "Design" },
    { "value": "DIREITO", "label": "Direito" },
    { "value": "ENFERMAGEM", "label": "Enfermagem" },
    { "value": "GESTAO_HOSPITALAR", "label": "Gestão Hospitalar" },
    { "value": "PROCESSOS_GERENCIAIS", "label": "Processos Gerenciais" },
    { "value": "GASTRONOMIA", "label": "Gastronomia" },
    { "value": "HISTORIA", "label": "Bacharel em História" },
    { "value": "MARKETING_DIGITAL", "label": "Marketing Digital" },
    { "value": "ENGENHARIA_COMPUTACAO", "label": "Engenharia da Computação" },
    { "value": "GESTAO_TI", "label": "Gestão da Tecnologia da Informação" },
    { "value": "SEGURANCA_INFORMACAO", "label": "Segurança da Informação" },
    { "value": "REDES_COMPUTADORES", "label": "Redes de Computadores" },
    { "value": "MARKETING", "label": "Marketing" },
    { "value": "TECNOLOGIAS_EDUCACIONAIS", "label": "Tecnologias Educacionais" },
    { "value": "PEDAGOGIA", "label": "Pedagogia Licenciatura" },
    { "value": "EDUCACAO_FISICA", "label": "Educação Física - Bacharelado" },
    { "value": "COMERCIO_EXTERIOR", "label": "Comércio Exterior" },
    { "value": "EMPREENDEDORISMO", "label": "Empreendedorismo" },
    { "value": "CIENCIAS_CONTABEIS", "label": "Ciências Contábeis" },
    { "value": "MEDIACAO", "label": "Mediação" },
    { "value": "ENGENHARIA_ELETRICA", "label": "Engenharia Elétrica" },
    { "value": "GESTAO_FINANCEIRA", "label": "Gestão Financeira" },
    { "value": "GESTAO_PRODUCAO_INDUSTRIAL", "label": "Gestão de Produção Industrial" },
    { "value": "ENGENHARIA_CIVIL", "label": "Engenharia Civil" },
    { "value": "SISTEMAS_PARA_INTERNET", "label": "Sistemas para Internet" }
]
